# Generated by Django 4.2.10 on 2024-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsiteuser',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
