# Generated by Django 4.2.10 on 2024-03-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_location_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=5000),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
