# Generated by Django 4.2.10 on 2024-03-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_report_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='common_issue',
            field=models.CharField(choices=[('1', 'Water Fountain Filter'), ('2', 'Clogging in Bathroom'), ('3', 'Bathroom Supply'), ('4', 'Classroom Equipment'), ('5', 'N/A')], default='5', max_length=2),
        ),
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='report-files/'),
        ),
    ]
