# Generated by Django 4.2.10 on 2024-03-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_report_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='files',
        ),
        migrations.CreateModel(
            name='SubmittedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='reports', to='app.submittedfiles'),
        ),
    ]
