# Generated by Django 4.2.10 on 2024-03-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_report_files_submittedfiles_report_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('1', 'Not Addressed'), ('2', 'In Progress'), ('3', 'Addressed')], default='1', max_length=2),
        ),
    ]
