# Generated by Django 4.2.10 on 2024-03-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reportsiteuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='status',
            new_name='equipment_status',
        ),
    ]
