# Generated by Django 4.2.11 on 2024-03-26 03:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_report_common_issue_alter_report_e_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_comment',
            field=models.FileField(blank=True, null=True, upload_to=app.models.report_file_path),
        ),
    ]
