# Generated by Django 4.2.11 on 2024-03-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_report_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin_comment',
            field=models.CharField(max_length=5000),
        ),
    ]
