# Generated by Django 4.2.10 on 2024-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_report_admin_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="receive_emails",
            field=models.CharField(
                choices=[
                    ("1", "receive_all"),
                    ("2", "receive_some"),
                    ("3", "receive_none"),
                ],
                default="1",
                max_length=25,
            ),
        ),
    ]
