# Generated by Django 4.2.11 on 2024-03-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_report_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('1', 'Aquatic and Fitness Center'), ('2', 'Astronomy Building'), ('3', 'Bryan Hall'), ('4', 'New Cabell Hall'), ('5', 'Chemistry Building'), ('6', 'Clark Hall'), ('7', 'Clemons Library'), ('8', 'Gilmer Hall'), ('9', 'Mechanical Engineering Building'), ('10', 'Minor Hall'), ('11', 'Newcomb Hall'), ('12', 'Olsson Hall'), ('13', 'Rice Hall'), ('14', 'Rotunda'), ('15', 'Other')], default='1', max_length=200),
        ),
    ]
