# Generated by Django 4.2.11 on 2024-03-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('1', 'Aquatic and Fitness Center'), ('2', 'Astronomy Building'), ('3', 'Bryan Hall'), ('4', 'Brown Library'), ('5', 'New Cabell Hall'), ('6', 'Cocke Hall'), ('7', 'Chemistry Building'), ('8', 'Clark Hall'), ('9', 'Clemons Library'), ('10', 'Gilmer Hall'), ('11', 'McLeod Hall'), ('12', 'Mechanical Engineering Building'), ('13', 'Minor Hall'), ('14', 'Monroe Hall'), ('15', 'Nau Hall'), ('16', 'Newcomb Hall'), ('17', 'Olsson Hall'), ('18', 'Rice Hall'), ('19', 'Rotunda'), ('20', 'Shannon Library'), ('21', 'Thornton Hall'), ('22', 'Other')], default='1', max_length=200),
        ),
    ]
