# Generated by Django 4.2.11 on 2024-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='receive_emails',
            field=models.CharField(choices=[('1', 'Receive All'), ('2', 'Receive Some'), ('3', 'Receive None')], default='3', max_length=25),
        ),
    ]
